ssh

diff --git a/.github/workflows/docker-build-and-push.yml b/.github/workflows/docker-build-and-push.yml
--- a/.github/workflows/docker-build-and-push.yml
+++ b/.github/workflows/docker-build-and-push.yml
@@ -10,7 +10,6 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
-    
       - name: Checkout repository
         uses: actions/checkout@v3
 
@@ -32,30 +31,26 @@ jobs:
           SERVER_USER: ${{ secrets.SERVER_USER }}
           IMAGE_NAME: sreekesh26/itemsapi
         run: |
-        
-          sudo apt-get update
-          sudo apt-get install -y sshpass
           mkdir -p ~/.ssh
           echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
           chmod 600 ~/.ssh/id_rsa
-
+          ssh-keyscan -H $SERVER_HOST >> ~/.ssh/known_hosts
           sshpass -p "$SSH_PRIVATE_KEY_PASSWORD" ssh -o StrictHostKeyChecking=no -o ConnectTimeout=30 $SERVER_USER@$SERVER_HOST << EOF
-          echo "Starting deployment process..."
-          set -x  
+            echo "Starting deployment process..."
+            set -x  
 
-          echo "Pulling Docker image..."
-          docker pull $IMAGE_NAME:latest
-          if [ $? -ne 0 ]; then echo "Error pulling image"; exit 1; fi
+            echo "Pulling Docker image..."
+            docker pull $IMAGE_NAME:latest
+            if [ $? -ne 0 ]; then echo "Error pulling image"; exit 1; fi
 
-          echo "Stopping existing container..."
-          docker stop itemsapi || true
-          docker rm itemsapi || true
-          if [ $? -ne 0 ]; then echo "Error stopping/removing container"; exit 1; fi
+            echo "Stopping existing container..."
+            docker stop itemsapi || true
+            docker rm itemsapi || true
+            if [ $? -ne 0 ]; then echo "Error stopping/removing container"; exit 1; fi
 
-          echo "Running new Docker container..."
-          docker run -d --name itemsapi -p 8080:8080 $IMAGE_NAME:latest
-          if [ $? -ne 0 ]; then echo "Error running container"; exit 1; fi
+            echo "Running new Docker container..."
+            docker run -d --name itemsapi -p 8080:8080 $IMAGE_NAME:latest
+            if [ $? -ne 0 ]; then echo "Error running container"; exit 1; fi
 
-          echo "Docker container deployed successfully!"
+            echo "Docker container deployed successfully!"
           EOF
-
